"""empty message

Revision ID: 3305e508370a
Revises: 6f50cc962957
Create Date: 2023-11-03 18:59:10.489200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3305e508370a'
down_revision = '6f50cc962957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
